spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb+srv://kadamvidya803_db_user:password@cluster0.g25ilub.mongodb.net/journaldb?appName=Cluster0&retryWrites=true&w=majority
spring.data.mongodb.database=journaldb
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassowrd
collection.name=journal_entries
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG