#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://kadamvidya803_db_user:l3zKtVuR6WlXFDVW@cluster0.g25ilub.mongodb.net/journaldb?appName=Cluster0&retryWrites=true&w=majority
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassowrd
collection.name=journal_entries